### ISSUE TITLE
Dependency Monitoring on us-west-2

### ISSUE THREAD

**Issue by allcentury** [awslabs/aws-well-architected-labs#210]
When I try to deploy [this stack](https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Operations/100_Dependency_Monitoring/Code/dependency_monitoring.yaml) to us-west-2 I consistently get an error saying that `t2.micro` is not available in the availability zone us-west-2d.  

I understand this needs to be region agnostic but is there a way to add a safe list of zone's that will work for others in all regions?  

Once I updated the Subnet and the Instance to `us-west-2a` the stack worked.

**Comment by TheFuz** [comment]
Hello,

Thank you for bringing this to our attention. CloudFormation is not capacity aware and the template was previously authored to randomly select an Availability Zone from the region when creating resources. As described in the following documentation (and what you essentially did), one of the ways to work around capacity issues is to retry the request in a different Availability Zone - in this case, deleting and recreating the stack. However, since the Availability Zone selection is random, there is a small probability that the same Availability Zone is selected again leading to another Insufficient Capacity issue.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-launch.html#troubleshooting-launch-capacity

To avoid this, I have updated the template and parameterized the Availability Zone in which resources are created. When deploying a stack with the updated template, you can make an arbitrary choice when selecting an Availability Zone. If you encounter an Insufficient Capacity issue, delete the current stack and create a new CloudFormation stack by choosing a different Availability Zone than what was previously used. This eliminates the possibility of a second request to the same Availability Zone that did not have enough capacity.

**Comment by allcentury** [comment]
Thank you for the quick attention this got!
