### ISSUE TITLE
fail_az.py seems to update only one single ASG

### ISSUE THREAD

**Issue by iwataka** [awslabs/aws-well-architected-labs#509]
I'm planning to use fail_az.py script in this repository to inject AZ failure for our system's testing.

I was checking the contents of that script and found that the below line seems to update only one single ASG.

https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Reliability/300_Testing_for_Resiliency_of_EC2_RDS_and_S3/Code/FailureSimulations/python/fail_az.py#L75

Is it a right behaviour or any mistakes ?
On the contrary, the below powershell script seems to update all ASG properly.

https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Reliability/300_Testing_for_Resiliency_of_EC2_RDS_and_S3/Code/FailureSimulations/powershell/fail_az.ps1#L21-L49

I've not tested that Python script yet, so please let me know if any misunderstanding.

Thank you for your support.

**Comment by setheliot** [comment]
Both code examples do the same thing.  They create a set of subnets that _excludes_ the "failed" AZ, and then update the Autoscaling Group to include only those subnets. Effectively the subnets in the "failed" AZ are excluded from the ASG.  

Does that make sense?

**Comment by setheliot** [comment]
Interesting observation.

To be clear, we do not consider this production-ready code, but instead it is lab-ready code that you can use to inform your own creation of production-ready code.

In the lab there is only one ASG.  The scripts make no effort to identify the _right_ ASG, and just simply assume there is only one ASG in the region. This would be a _bad_ assumption in production. For the lab we deploy a workload with only one ASG, so this assumption works fine. In your case you are creating your own workload, which breaks the lab assumption

It looks from the code that both Python and PowerShell grab all ASG.  The difference is the Python script does not even bother to loop through them, while the PS script does.

Yes, this is something we can certainly improve in the scripts, but it is not a high priority -- these scripts have been mostly unchanged since 2018, and you are the _first_ to notice this. I really appreciate your attention to detail!

If you would like to change the scripts to only use the _right_ ASG we gladly accept PRs, so would be happy for you to make these fixes.

I will leave this issue open for a while, so you can link to it if you would like to make a PR

**Comment by iwataka** [comment]
I understand what you said.

In my opinion, all the implementations of `fail_az` should be at least consisntent (in case of the above comment, python and powershell should do the same logic).

And I think the scripts should update all ASGs which belongs to the "failed" AZ (in other words, poweshell's implementation is better than python's one) because there're multiple ASGs in most real cases.
I will try to fix like that.
I will appreciate to help me when creating a PR.

**Comment by setheliot** [comment]
> I will appreciate to help me when creating a PR.

This seems to cover it well https://www.dataschool.io/how-to-contribute-on-github/

**Comment by iwataka** [comment]
Thank you for merging the PR.
I close this issue.
